export const GET_MOVIES = 'GET_MOVIES';
export const GET_FILTERED_MOVIES = 'GET_FILTERED_MOVIES'
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
export const LOAD_MORE_MOVIES = 'LOAD_MORE_MOVIES'
export const SET_SELECTED_YEAR = 'SET_SELECTED_YEAR'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'
export const GENRES_ID = 'GENRES_ID'
export const SEARCH_MOVIES = 'SEARCH_MOVIES'
export const SHOW_MOVIES_DETAILS= 'SHOW_MOVIES_DETAILS'

